# Generated by Django 5.1.4 on 2025-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Inventory',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
